### ISSUE TITLE
Inconsistent timeouts when run with short (< 5m) delays

### ISSUE THREAD

**Issue by jamilbk** [ChromaxS/challenge-icmprs#3]
On my M1, it seems I am getting weirdly inconsistent timeouts with short delays (< 5ms):

```
root@0c817bcf87b3:/usr/src/app# target/release/icmprs 1.1.1.1,10,2
1.1.1.1,1,6983
1.1.1.1,2,6977
1.1.1.1,3,7284
1.1.1.1,4,7311
1.1.1.1,5,7442
1.1.1.1,6,9068
1.1.1.1,7,6839
1.1.1.1,8,8516
1.1.1.1,9,9817
1.1.1.1,10,-1
```

Delays of `5ms` and higher work fine:

```
root@0c817bcf87b3:/usr/src/app# target/release/icmprs 1.1.1.1,10,5
1.1.1.1,1,9396
1.1.1.1,2,8431
1.1.1.1,3,9004
1.1.1.1,4,7711
1.1.1.1,5,7486
1.1.1.1,6,9020
1.1.1.1,7,6707
1.1.1.1,8,8017
1.1.1.1,9,9255
1.1.1.1,10,7758
```

I wonder if there might be some race condition sending packets that quickly through the socket. Perhaps `AsyncFd` could be used to send as well as receive?

**Comment by ChromaxS** [comment]
This looks to be a regression introduced by: 511a1f2df879

It works in the commit prior:
```
icmprs ((HEAD detached at 21a35b7)) $ cargu build && sudo target/debug/icmprs 192.168.2.1,10,1
# omitted build output
192.168.2.1,1,523
192.168.2.1,2,1714
192.168.2.1,3,2949
192.168.2.1,4,4186
192.168.2.1,5,5433
192.168.2.1,6,6661
192.168.2.1,7,6678
192.168.2.1,8,7921
192.168.2.1,9,9160
192.168.2.1,10,10389
```

I refactored the output to be in a common place and accidentally changed the CSV output to be the round trip time micros instead of micros elapsed since program start. To clarify, should it actually be the latter? I'll submit a PR to address that.

I believe the socket should be taking the data as fast as the program can send it to the kernel as the socket is set to blocking... so if it was an async issue, it'd manifest as a EAGAIN/EWOULDBLOCK.
